version: '3'

services:
  db:
    container_name: postgres_sneakers
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sneakers_db
    ports:
      - "5435:5432"

  pgadmin:
    container_name: pgadmin_sneackers
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"